---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base:latest

include:
  - 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'
  - project: lb-experts/golbclient
    file: .gitlab-ci_go.yml
    ref: psaiz_devel

variables:
  KOJI_TAG: 'lb'
  KOJI_TAG_7: 'ai7'

  BUILD_7: 'True'
  BUILD_8: 'True'

  DIST_8: .el8
  DIST_7: .ai7
  DIST_6: .ai6

.patch_version: &patch_version |
    RELEASE=`grep 'Release = "' main.go | awk -F \" '{print $2}'`
    VERSION=`grep 'Version = "' main.go | awk -F \" '{print $2}'`
    cat ermis.spec.tpl  | sed "s/#REPLACE_BY_VERSION#/$VERSION/" | sed "s/#REPLACE_BY_RELEASE#/$RELEASE/" > ermis.spec

.rpm_deps:
  before_script:
    - *patch_version
    - yum-builddep -y *.spec

build_srpm7:
  before_script:
    - *patch_version
    - yum-builddep -y --disableplugin=protectbase,priorities *.spec

build_rpm7:
  before_script:
    - *patch_version
    - yum-builddep -y --disableplugin=protectbase,priorities *.spec

