---
image: gitlab-registry.cern.ch/linuxsupport/cc7-base:latest

include:
  - 'https://gitlab.cern.ch/linuxsupport/rpmci/raw/master/rpm-ci.yml'
  - project: lb-experts/golbclient
    file: .gitlab-ci_go.yml
    ref: psaiz_devel

variables:
  KOJI_TAG: 'lb'
  KOJI_TAG_7: 'ai7'

  BUILD_7: 'True'
  BUILD_8: 'True'

  DIST_8: .el8
  DIST_7: .ai7
  DIST_6: .ai6

.patch_version: &patch_version |
    RELEASE=`grep 'Release = "' main.go | awk -F \" '{print $2}'`
    VERSION=`grep 'Version = "' main.go | awk -F \" '{print $2}'`
    cat ermis.spec.tpl  | sed "s/#REPLACE_BY_VERSION#/$VERSION/" | sed "s/#REPLACE_BY_RELEASE#/$RELEASE/" > ermis.spec

.rpm_deps:
  before_script:
    - *patch_version
    - yum-builddep -y *.spec

build_srpm7:
  before_script:
    - *patch_version
    - yum-builddep -y --disableplugin=protectbase,priorities *.spec

build_rpm7:
  before_script:
    - *patch_version
    - yum-builddep -y --disableplugin=protectbase,priorities *.spec
    
behave:
  image: gitlab-registry.cern.ch/ai-config-team/ai-tools
  stage: prebuild
  allow_failure: false
  script:
    - yum -y install python2-behave krb5-workstation
    - cd  tests/behave
    - echo $ERMISTST_DECODED | kinit ermistst@CERN.CH
    - klist
    - behave . -D ermistst=$ERMISTST -D ermists=$ERMISTS

landb:
  image: gitlab-registry.cern.ch/ai-config-team/ai-tools
  stage: prebuild
  allow_failure: false
  script:
    - echo "READY TO DO THE SOAP CALL"
    - mkdir -p /usr/local/etc /etc/httpd/conf/
    - cp tests/landb/goermis.yaml /usr/local/etc/goermis.yaml
    - sed -i -e "s/##REPLACE_BY_USER##/${SOAPUSER}/g" /usr/local/etc/goermis.yaml
    - sed -i -e "s/##REPLACE_BY_PASSWORD##/${SOAPPASSWORD}/g" /usr/local/etc/goermis.yaml
    - cd tests/landb
    - yum-builddep -y --disableplugin=protectbase,priorities *.spec
    - yum install -y golang gcc
    - go version
    - echo "$ERMISCERT" > /etc/httpd/conf/ermiscert.pem
    - echo "$ERMISKEY" > /etc/httpd/conf/ermiskey.pem
    - ls -al /etc/httpd/conf/
    - chmod 600 /etc/httpd/conf/ermiscert.pem /etc/httpd/conf/ermiskey.pem
    - go test .



build_docker_image_stable:
  image: gitlab-registry.cern.ch/ci-tools/docker-image-builder:latest
  stage: prebuild
  script: "echo"
  tags:
    - docker-image-build
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}

