FROM golang-1.15.8
LABEL maintainer="LB-Experts <lb-experts@cern.ch>"
RUN   yum -y install  git  
COPY .  .
RUN go mod download
RUN go build -o goermis .
RUN  mkdir -p  /var/lib/ermis/ /var/log/ermis/
COPY staticfiles      /var/lib/ermis/staticfiles
COPY templates        /var/lib/ermis/templates
EXPOSE 8080
ENTRYPOINT ["/goermis"]
CMD ["-config=/usr/local/etc/goermis.yaml", "-home=/var/lib/ermis/"]
