---
apiVersion: v1
kind: Service
metadata:
    name: goermis-service
spec:
    type: ClusterIP
    selector:
        app: goermis
    ports:
        - name: https
          port: 443
          targetPort: 443
          protocol: TCP


