apiVersion: apps/v1
kind: Deployment
metadata:
  name: goermis-deployment
  labels:
    app: goermis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goermis
  template:
    metadata:
      labels:
        app: goermis
    spec:
      containers:
        - name: httpd
          image: gitlab-registry.cern.ch/lb-experts/k8s/httpd:master
          imagePullPolicy: "Always"
          volumeMounts:
            - name: oidc
              mountPath: "/etc/httpd/conf_ssl/"
              readOnly: true
            - name: ermis-certs
              mountPath: "/etc/httpd/ssl/"
              readOnly: true
          command: ["/bin/bash","-c", "cp /etc/httpd/conf_ssl/oidc_secrets.conf /etc/httpd/conf/; httpd -D FOREGROUND"]
#          command: ["sleep", "3600"]
        - name: goermis
          image: gitlab-registry.cern.ch/lb-experts/goermis:httpd
          imagePullPolicy: "Always"

          volumeMounts:
            - name: ermis-certs
              mountPath: "/etc/ssl/certs/"
              readOnly: true
            - name: configfile
              mountPath: "/usr/local/etc/"
              readOnly: true
          ports:
            - containerPort: 8080
          command: ["sleep","3600"]

      volumes:
        - name: ermis-certs
          secret:
            secretName: ermis-certs
        - name: configfile
          secret:
            secretName: config
        - name: oidc
          secret: 
            secretName: oidc-conf
            items: 
              - key: oidc_secrets.conf
                path: oidc_secrets.conf
      imagePullSecrets:
        - name: regcred-lb-experts
