apiVersion: apps/v1
kind: Deployment
metadata:
  name: goermis-deployment
  labels:
    app: goermis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goermis
  template:
    metadata:
      labels:
        app: goermis
    spec:
      containers:
        - name: httpd
          image: gitlab-registry.cern.ch/lb-experts/k8s/httpd:psaiz_devel
          imagePullPolicy: "Always"
          volumeMounts:
            - name: oidc
              mountPath: "/etc/httpd/conf_ssl/"
              readOnly: true
            - name: ermis-certs
              mountPath: "/etc/httpd/ssl/"
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                 - /bin/sh
                 - -c
                 - cp /etc/httpd/conf_ssl/oidc_secrets.conf /etc/httpd/conf
          command: ["sleep","3600"]
        - name: goermis
          image: gitlab-registry.cern.ch/lb-experts/goermis:latest
          args: 
            - "-config=/usr/local/etc/goermis.yaml"
            - "-home=/var/lib/ermis/"           
          volumeMounts:
            - name: ermis-certs
              mountPath: "/etc/ssl/certs/"
              readOnly: true
            - name: configfile
              mountPath: "/usr/local/etc/"
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: ermis-certs
          secret:
            secretName: ermis-certs
        - name: configfile
          secret:
            secretName: config
        - name: oidc
          secret: 
            secretName: oidc-conf
            items: 
              - key: oidc_secrets.conf
                path: oidc_secrets.conf
      imagePullSecrets:
        - name: regcred-lb-experts
