---
apiVersion: v1
kind: Service
metadata:
    name: goermis-service
spec:
    type: ClusterIP
    selector:
        app: goermis
    ports:
        - name: https
          port: 8080
          targetPort: 8080
          protocol: TCP


