apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: gitlab-registry.cern.ch/lb-experts/goermis/httpd-proxy:latest
          volumeMounts:
            - name: ermis-certs
              mountPath: "/etc/ssl/certs/"
              readOnly: true
            - name: configfile
              mountPath: "/usr/local/etc/"
              readOnly: true
            - name: ca-bundle
              mountPath: "/etc/ssl/certs/"
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: ermis-certs
          secret:
            secretName: ermis-certs
        - name: configfile
          secret:
            secretName: config
        - name: ca-bundle
          secret:
            secretName: ca-bundle
      imagePullSecrets:
        - name: regcred
