---
apiVersion:  extensions/v1beta1
kind: Ingress
metadata:
  name: goermis-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "*.cern.ch"
    http:
      paths:
      - path: /lbweb
        backend:
          serviceName: goermis-service
          servicePort: 8080
  tls:
  - hosts:
    - goermis-sjhkk6amxph2-node-0.cern.ch

  