---
    apiVersion:  extensions/v1beta1
    kind: Ingress
    metadata:
      name: goermis-ingress
      namespace: default
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "https"
    spec:
        rules:
        - host: goermisk8s.cern.ch
          http:
            paths:
            - path: /
              backend:
                serviceName: goermis-service
                servicePort: 443
        tls:
        - hosts:
          - goermisk8s.cern.ch
    
      
    